---

version: '3'

services:
  exercises:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/exercises-java
    command: make lint-descriptions lint-code test schema-validate
